### ISSUE TITLE
How to change width of search form ?

### ISSUE THREAD

**Issue by kokotko1337** [Klap-in/dokuwiki-plugin-searchform#4]
literally tittle .. 
i can not found any options

**Comment by csporrer** [comment]
The possibility to change the size of the search form would be very helpful and more user-friendly.

**Comment by Klap-in** [comment]
You can apply userstyling, in the latest version the input field has the class 'searchform__qsearch_in'.

If you create in the `conf/` folder the file `conf/userstyle.css` with the styling (or add it if it already exists):
```css 
/* set custom width for input fields of searchform plugin */
form.search input.searchform__qsearch_in {
    width: 30em;
}
```
